export const NIGERIAN_UNIVERSITIES = [
  "University of Lagos (UNILAG)",
  "Obafemi Awolowo University (OAU)",
  "University of Ibadan (UI)",
  "University of Nigeria, Nsukka (UNN)",
  "Ahmadu Bello University (ABU)",
  "University of Benin (UNIBEN)",
  "University of Port Harcourt (UNIPORT)",
  "University of Ilorin (UNILORIN)",
  "Lagos State University (LASU)",
  "Federal University of Technology, Akure (FUTA)",
  "Federal University of Technology, Owerri (FUTO)",
  "Federal University of Technology, Minna (FUTMINNA)",
  "Covenant University",
  "Babcock University",
  "Bowen University",
  "Nile University of Nigeria",
  "Landmark University",
  "Afe Babalola University (ABUAD)",
  "Nnamdi Azikiwe University (UNIZIK)",
  "University of Calabar (UNICAL)",
  "University of Jos (UNIJOS)",
  "University of Abuja (UNIABUJA)",
  "Delta State University (DELSU)",
  "Rivers State University (RSU)",
  "Ekiti State University (EKSU)",
  "Olabisi Onabanjo University (OOU)",
  "Chukwuemeka Odumegwu Ojukwu University (COOU)",
  "Enugu State University of Science and Technology (ESUT)",
  "Ambrose Alli University (AAU)",
  "Adekunle Ajasin University (AAUA)",
  "Bayero University Kano (BUK)",
  "Usmanu Danfodiyo University (UDUS)",
  "Madonna University",
  "Pan-Atlantic University (PAU)",
  "Lead City University",
  "Redeemers University",
  "Caleb University",
  "Bells University of Technology",
  "Mountain Top University",
  "Other / Custom Institution"
];
