/**
 * Complete list of all Federal, State, and accredited Private Universities in Nigeria
 * Sorted alphabetically for seamless search and dropdown selection.
 */
export const NIGERIAN_UNIVERSITIES: string[] = [
  "Abia State University, Uturu (ABSU)",
  "Abubakar Tafawa Balewa University, Bauchi (ATBU)",
  "Achievers University, Owo",
  "Adamawa State University, Mubi (ADSU)",
  "Adekunle Ajasin University, Akungba-Akoko (AAUA)",
  "Adeleke University, Ede",
  "Admiralty University of Nigeria, Ibusa",
  "Afe Babalola University, Ado-Ekiti (ABUAD)",
  "African University of Science and Technology, Abuja (AUST)",
  "Ahmadu Bello University, Zaria (ABU)",
  "Ahman Pategi University, Patigi",
  "Air Force Institute of Technology, Kaduna (AFIT)",
  "Ajayi Crowther University, Oyo",
  "Akwa Ibom State University, Ikot Akpaden (AKSU)",
  "Al-Ansar University, Maiduguri",
  "Al-Bayan University, Ankpa",
  "Al-Hikmah University, Ilorin",
  "Al-Istiqama University, Sumaila",
  "Al-Qalam University, Katsina",
  "Alex Ekwueme Federal University, Ndufu-Alike (AE-FUNAI)",
  "Amadeus University, Amato",
  "Ambrose Alli University, Ekpoma (AAU)",
  "American University of Nigeria, Yola (AUN)",
  "Anchor University, Ayobo, Lagos",
  "Arthur Jarvis University, Akpabuyo",
  "Atiba University, Oyo",
  "Augustine University, Ilara, Epe",
  "Babcock University, Ilishan-Remo",
  "Bamidele Olumilua University of Education, Science and Technology, Ikere-Ekiti (BOUESTI)",
  "Bauchi State University, Gadau (BASUG)",
  "Bayelsa Medical University, Yenagoa (BMU)",
  "Bayero University, Kano (BUK)",
  "Baze University, Abuja",
  "Bells University of Technology, Ota",
  "Benson Idahosa University, Benin City (BIU)",
  "Benue State University, Makurdi (BSUM)",
  "Bingham University, Karu",
  "Borno State University, Maiduguri (BOSU)",
  "Bowen University, Iwo",
  "Caleb University, Imota, Lagos",
  "Capital City University, Kano",
  "Caritas University, Amorji-Nike, Enugu",
  "Chrisland University, Abeokuta",
  "Christopher University, Mowe",
  "Chukwuemeka Odumegwu Ojukwu University, Uli (COOU)",
  "Clifford University, Ihie, Abia",
  "Coal City University, Enugu",
  "Confluence University of Science and Technology, Osara (CUSTECH)",
  "Covenant University, Ota",
  "Crawford University, Igbesa",
  "Crescent University, Abeokuta",
  "Cross River University of Technology / UNICROSS, Calabar",
  "Delta State University of Science and Technology, Ozoro",
  "Delta State University, Abraka (DELSU)",
  "Dennis Osadebay University, Asaba",
  "Dominican University, Ibadan",
  "Dominion University, Ibadan",
  "Eastern Palm University / K.O. Mbadiwe University, Ogboko",
  "Ebonyi State University, Abakaliki (EBSU)",
  "Edo State University, Uzairue",
  "Edusoko University, Bida",
  "Edwin Clark University, Kiagbodo",
  "Ekiti State University, Ado-Ekiti (EKSU)",
  "Eko University of Medicine and Health Sciences, Ijanikin",
  "Elizade University, Ilara-Mokin",
  "Emmanuel Alayande University of Education, Oyo",
  "Enugu State University of Medical and Applied Sciences, Igbo-Eno (SUMAS)",
  "Enugu State University of Science and Technology, Enugu (ESUT)",
  "European University of Nigeria, Abuja",
  "Evangel University, Akaeze",
  "Federal University of Agriculture, Abeokuta (FUNAAB)",
  "Federal University of Agriculture, Zuru",
  "Federal University of Health Sciences, Azare",
  "Federal University of Health Sciences, Ila-Orangun",
  "Federal University of Health Sciences, Otukpo",
  "Federal University of Petroleum Resources, Effurun (FUPRE)",
  "Federal University of Technology, Akure (FUTA)",
  "Federal University of Technology, Babura",
  "Federal University of Technology, Ikot Abasi",
  "Federal University of Technology, Minna (FUTMINNA)",
  "Federal University of Technology, Owerri (FUTO)",
  "Federal University, Birnin Kebbi (FUBK)",
  "Federal University, Dutse (FUD)",
  "Federal University, Dutsin-Ma (FUDMA)",
  "Federal University, Gashua (FUGASHUA)",
  "Federal University, Gusau (FUGUS)",
  "Federal University, Kashere (FUKASHERE)",
  "Federal University, Lafia (FULAFIA)",
  "Federal University, Lokoja (FULOKOJA)",
  "Federal University, Otuoke (FUOTUOKE)",
  "Federal University, Oye-Ekiti (FUOYE)",
  "Federal University, Wukari (FUWUKARI)",
  "Fountain University, Osogbo",
  "Franco-British International University, Kaduna",
  "Glorious Vision University, Ogwa",
  "Godfrey Okoye University, Ugwuomu-Nike, Enugu",
  "Gombe State University of Science and Technology, Kumo",
  "Gombe State University, Tudun Wada (GSU)",
  "Greenfield University, Kaduna",
  "Gregory University, Uturu",
  "Hallmark University, Ijebu-Itele",
  "Havilla University, Nde-Ikom",
  "Hensen University, Benin City",
  "Hezekiah University, Umudi",
  "Hillside University of Science and Technology, Okemesi",
  "Ibrahim Badamasi Babangida University, Lapai (IBBU)",
  "Iconic Open University, Sokoto",
  "Igbinedion University, Okada",
  "Ignatius Ajuru University of Education, Port Harcourt (IAUE)",
  "Imo State University, Owerri (IMSU)",
  "James Hope University, Lekki, Lagos",
  "Jewel University, Gombe",
  "Joseph Ayo Babalola University, Ikeji-Arakeji (JABU)",
  "Kaduna State University, Kaduna (KASU)",
  "Kano University of Science and Technology, Wudil (KUST)",
  "Karl Kumm University, Vom",
  "Kebbi State University of Science and Technology, Aliero (KSUSTA)",
  "Khadija University, Majia",
  "Khalifa Isiyaku Rabiu University, Kano",
  "Kingsley Ozumba Mbadiwe University, Ogboko (KOMU)",
  "Kogi State University, Anyigba (Prince Abubakar Audu University)",
  "Kogi State University, Kabba",
  "Koladaisi University, Ibadan",
  "Kwara State University, Malete (KWASU)",
  "Kwararafa University, Wukari",
  "Ladoke Akintola University of Technology, Ogbomoso (LAUTECH)",
  "Lagos State University of Education, Ijanikin (LASUED)",
  "Lagos State University of Science and Technology, Ikorodu (LASUSTECH)",
  "Lagos State University, Ojo (LASU)",
  "Landmark University, Omu-Aran",
  "Lead City University, Ibadan",
  "Legacy University, Okija",
  "Lux Mundi University, Umuahia",
  "Maduka University, Ekwegbe-Nsukka",
  "Madonna University, Elele",
  "Maitama Sule University, Kano (YUMSUK)",
  "Margaret Lawrence University, Galilee",
  "Maryam Abacha American University of Nigeria, Kano",
  "Mcpherson University, Seriki Sotayo",
  "Mercy Medical University, Iwo",
  "Mewar International University, Masaka",
  "Michael Okpara University of Agriculture, Umudike (MOUAU)",
  "Miva Open University, Abuja",
  "Modibbo Adama University, Yola (MAU)",
  "Moshood Abiola University of Science and Technology, Abeokuta",
  "Mountain Top University, Makogi Oba",
  "Nasarawa State University, Keffi (NSUK)",
  "National Open University of Nigeria (NOUN)",
  "Newgate University, Minna",
  "Niger Delta University, Wilberforce Island (NDU)",
  "Nigeria Police Academy, Wudil (POLAC)",
  "Nigerian Army University, Biu (NAUB)",
  "Nigerian British University, Asa",
  "Nigerian Defence Academy, Kaduna (NDA)",
  "Nigerian Maritime University, Okerenkoko",
  "Nile University of Nigeria, Abuja",
  "Nnamdi Azikiwe University, Awka (UNIZIK)",
  "Novena University, Ogume",
  "Obafemi Awolowo University, Ile-Ife (OAU)",
  "Obong University, Obong Ntak",
  "Oduduwa University, Ipetumodu",
  "Olabisi Onabanjo University, Ago-Iwoye (OOU)",
  "Olusegun Agagu University of Science and Technology, Okitipupa (OAUSTECH)",
  "Osun State University, Osogbo (UNIOSUN)",
  "PAMO University of Medical Sciences, Port Harcourt",
  "Pan-Atlantic University, Ibeju-Lekki (PAU)",
  "Paul University, Awka",
  "PeaceLand University, Enugu",
  "PEN Resource University, Gombe",
  "Peter University, Achina-Onitsha",
  "Philomath University, Kuje, Abuja",
  "Plateau State University, Bokkos (PLASU)",
  "Precious Cornerstone University, Ibadan",
  "Prime University, Kuje, Abuja",
  "Redeemer's University, Ede",
  "Renaissance University, Ugbawka",
  "Rhema University, Obeama-Asa",
  "Ritman University, Ikot Ekpene",
  "Rivers State University, Port Harcourt (RSU)",
  "Sa'adatu Rimi University of Education, Kumbotso",
  "Salem University, Lokoja",
  "Shanahan University, Onitsha",
  "Shehu Shagari University of Education, Sokoto",
  "Skyline University Nigeria, Kano",
  "Sokoto State University, Sokoto (SSU)",
  "Southwestern University, Okun-Owa",
  "Spiritan University, Nneochi",
  "Sule Lamido University, Kafin Hausa (SLU)",
  "Summit University, Offa",
  "Tai Solarin University of Education, Ijagun (TASUED)",
  "Tansian University, Umunya",
  "Taraba State University, Jalingo (TSU)",
  "Thomas Adewumi University, Oko",
  "Topfaith University, Mkpatak",
  "Trinity University, Yaba, Lagos",
  "Umar Musa Yar'Adua University, Katsina (UMYU)",
  "University of Abuja, Gwagwalada (UNIABUJA)",
  "University of Africa, Toru-Orua",
  "University of Agriculture and Environmental Sciences, Umuagwo",
  "University of Benin, Benin City (UNIBEN)",
  "University of Calabar, Calabar (UNICAL)",
  "University of Cross River State (UNICROSS)",
  "University of Delta, Agbor",
  "University of Ibadan, Ibadan (UI)",
  "University of Ilesa, Osun State",
  "University of Ilorin, Ilorin (UNILORIN)",
  "University of Jos, Jos (UNIJOS)",
  "University of Lagos, Akoka (UNILAG)",
  "University of Maiduguri, Maiduguri (UNIMAID)",
  "University of Mkar, Mkar, Gboko",
  "University of Nigeria, Nsukka (UNN)",
  "University of Offa, Kwara",
  "University of Port Harcourt, Port Harcourt (UNIPORT)",
  "University of Uyo, Uyo (UNIUYO)",
  "Usmanu Danfodiyo University, Sokoto (UDUS)",
  "Veritas University, Bwari, Abuja",
  "Wellspring University, Irhirhi, Benin City",
  "Wesley University, Ondo",
  "Western Delta University, Oghara",
  "Westland University, Iwo",
  "Wigwe University, Isiokpo",
  "Yobe State University, Damaturu (YSU)",
  "Yusuf Maitama Sule University, Kano (YUMSUK)",
  "Zamfara State University, Talata Mafara (ZAMSU)",
  "Other / Custom Institution"
];
